language: python
python:
  - 2.7
  - 3.4
# command to install dependencies
#install: "pip install -r requirements.txt"

install:
  - python setup.py install

before_script:
 - chmod +x tests/test_client.py

# command to run tests
script: tests/test_client.py
